SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
	FROM BOOK
    	INNER JOIN AUTHOR
        	ON BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
    WHERE BOOK.CATEGORY LIKE '경제'
    ORDER BY BOOK.PUBLISHED_DATE ASC